import { ICity, IState, ICountry } from '@nutela/models/core-data';
import { IPersonal } from './personal.interface';

export interface IReboardContact {
  area_kin: ICity;
  // area_kin?:number;
  area_kin_city_id: number;
  area_kin_description: string;
  area_p: ICity;
  // area_p:number;
  area_p_city_id: number;
  area_r: ICity;
  // area_r:number;
  area_r_city_id: number;
  country_kin: ICountry;
  // country_kin:number;
  country_kin_nationality_id: number;
  country_kin_description:string;
  state_kin_description:string;
  country_p: ICountry;
  // country_p:number;
  country_p_nationality_id: number;
  country_p_description:string;
  state_p_description:string;
  area_p_description:string;
  country_r: ICountry;
  // country_r:number;
  country_r_nationality_id: number;
  country_r_description: string;
  state_r_description:string;
  area_r_description:string;
  email: string;
  email_kin: string;
  email_personal: string;
  employeeInfo: IPersonal;
  employeecontact_id: number;
  fax: string;
  gsm: string;
  image_kin: string;
  img_extension_nextofkin: string;
  kin_Surname: string;
  kin_firstname: string;
  kin_gender: string;
  kin_otherNames: string;
  kin_relationship: string;
  kin_title: string;
  mobile_phone: string;
  office_ext: string;
  pager: string;
  phone: string;
  state_kin: IState;
  // state_kin:number;
  state_kin_state_id: number;
  state_p: IState;
  // state_p:number;
  state_p_state_id: number;
  state_r: IState;
  // state_r:number;
  state_r_state_id: number;
  street1_kin: string;
  street1_p: string;
  street1_r: string;
  street2_kin: string;
  street2_p: string;
  street2_r: string;
  tel1_kin: string;
  tel2_kin: string;
  zip_kin: string;
  zip_p: string;
  zip_r: string;
  same_address: boolean;
  img_size: number;
  imageOversized: boolean;
  doc_binary: string;
  doc_guid: string;
  doc_url: string;
  doc_extension: string;
  doc_size: number;
  doc_mimetype: string;
  is_v2_update: boolean;
  preferred_email: string;
  kin_has_attachment: boolean;
}
