import { IEmployee } from './employee.interface'
import { ILoanDefinitionInfo } from './loan-definition-info.interface';
import { ICurrency } from './currency.interface';

export interface IApprovedLoan {
  status: number,
  loandetail_id: number,
  loanDefInfo: ILoanDefinitionInfo,
  EmployeeInfo: IEmployee,
  book_date: Date,
  CurrencyInfo: ICurrency,
  ess_source_id: number,
  initial_loan_amount: number,
  effective_period: Date,
  monthly_deduction: number,
  interest_rate: number,
  tenor_years: number,
  tenor_months: number,
  tenor_days: number,
  loan_balance: number,
  uncleared_loan_balance: number,
  overdue_monthly_ded: number,
  overdue_monthly_interest: number,
  moratorium: number,
  disburse_transaction_date: Date,
  disburse_actual_date: Date,
  first_deduction_date: Date,
  disburse_status: number,
  disburse_note: string,
  prior_effective_date: Date,
  sys_note: string,
  manual_repay_bal: number,
  manual_repay_int: number,
  has_applied: boolean,
  doc_extension: string,
  doc_binary: string,
  doc_url: string,
  doc_guid: string,
  doc_size: string,
  employeeInfo: string,
  loan_amount: number,
  loanTypeDescription: string,
  narration: string,
  effective_date: Date,
  loanDefinition: string
}
