export enum Sources {
  ITEMS_AWAITING_MY_ACTIONS = 0,
  MY_SUBMISSIONS = 1
}

export enum msgSources {
  LEAVEDETAILS = 'LEAVEDETAILS',
  PERFORMANCE_OBJECTIVES = 'PERFORMANCE_OBJECTIVES',
  EMPLOYEE_RESIGNATION = 'EMPLOYEE_RESIGNATION',
  EMPLOYEE_RESIGNATION_HR = 'EMPLOYEE_RESIGNATION_HR',
  EMPLOYEE_REBOARDING = 'EMPLOYEE_REBOARDING'
}
