export const APP_AREAS = {
  "SELF_SERVICE": "SELF_SERVICE",
  "HR_ADMINISTRATION": "HR_ADMINISTRATION",
  "WORKFORCE": "WORKFORCE",
  "TALENT": "TALENT",
  "COMPENSATION": "COMPENSATION",
  "PLATFORM": "PLATFORM",
  "ENTERPRISE_PLANNING_AND_JOB_MODELLING": "ENTERPRISE_PLANNING_AND_JOB_MODELLING",
  "BUSINESS_PARTNERING": "BUSINESS_PARTNERING"
};
