import { IAnalysisDetail } from "./analysis-detail.interface";
import { IEnterpriseStructureType } from "./ent-structure-type.interface";
import { IEmployeeDetail } from "./employee-detail.interface";
import { IDesignation } from "./designation.interface";
import { IPosition } from "./positions.interface";
import { IStaffCategory } from "./staff-category.interface";
import { IPaygroup } from "./paygroup.interface";
import { IPaygrade } from "./paygrade.interface";

export interface IProvisioning{
  id: number
  staff_category_id: number;
  employee_number: string;
  title: string;
  employee_surname: string;
  employee_midname: string;
  employee_firstname: string;
  gender: string;
  PaygroupInfo: IPaygroup;
  PaygradeInfo: IPaygrade;
  date_of_birth: Date;
  rec_category: number;
  user_on_ad: boolean;
  sync_firstname: string;
  sync_surname: string;
  username: string;
  send_creation_email_to: number;
  creation_email_custom: string;
  designation_id: number;
  position_id: number;
  reports_to: number;
  employment_date: Date;
  a_confirm_date: Date;
  backup_officer_id: number;
  is_permanent_staff: boolean;
  emp_duration_from: Date;
  emp_duration_to: Date;
  ent_struc_type_id: number;
  ent_struc_details_id: number;
  on_payroll: boolean;
  paygroup_id: number;
  grade_id: number;
  compute_pension: boolean;
  compute_nhf: boolean;
  compute_tax: boolean;
  employee_id: number;
  pay_newstaff_arrears: boolean;
  user_type: number;
  provision_id: number;
  cost_center: string;
  roleNames: Array<any>;
  AnalysisDetailsInfo: IAnalysisDetail;
  AnalysisInfo: IEnterpriseStructureType;
  BackUpOfficerInfo: IEmployeeDetail;
  DesignationInfo: IDesignation;
  EmployeeInfo: IEmployeeDetail;
  PositionInfo: IPosition;
  StaffcategoryInfo: IStaffCategory;
  SupervisorInfo: IEmployeeDetail;
  status: number;
  editing: number;
  sys_message: string;
}
