export enum NavMenuItemTypes {
  PERSONAL_INFORMATION = 'PERSONAL_INFORMATION',
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  CONTACT = 'CONTACT',
  IDENTIFICATION = 'IDENTIFICATION',
  PAYMENT = 'PAYMENT',
  WORK_HISTORY = 'WORK_HISTORY',
  EDUCATIONAL_HISTORY = 'EDUCATIONAL_HISTORY',
  PROFESSIONAL_QUALIFICATIONS = 'PROFESSIONAL_QUALIFICATIONS',
  DEPENDANTS = 'DEPENDANTS',
  BENEFICIARIES = 'BENEFICIARIES',
  PERSONAL_REFEREES = 'PERSONAL_REFEREES',
  GUARANTORS = 'GUARANTORS',
  FAMILY = 'FAMILY',
  CUSTOM_DATA_FORM = 'CUSTOM_DATA_FORM',
  NONE = 'NONE'
}
