export interface IPayrollDeduction {
  deduction_id: number,
  code: string,
  description: string,
  deduct_frequency: number,
  max_deduct: number,
  start_period: string,
  deduct_at_startPeriod: boolean,
  shortname: string,
  prorate_deduction: boolean,
  payroll_type: number,
  is_statutory: boolean,
  eligibility: number,
  cumulate_deduction: boolean,
  cumulate_deduction_id: number,
  deduct_usedirect_amount: boolean,
  deduct_currency_id: number,
  deduct_amount: number,
  deduct_formula_id: number,
  has_employer_contribution: boolean,
  empcontibute_usedirect_amount: boolean,
  empcontribute_amount: number,
  empcontribute_formula_id: number,
  group_item: boolean,
  groupname_id: number,
  deductitem_type: number,
  rank: number,
  ledger_account: string,
  can_subscribe: boolean,
  non_exclusion: boolean,
  temp_or_perm: boolean,
  eff_period_from: Date,
  eff_period_to: Date,
  payroll_profile: number,
  link_to: boolean,
  link_deduction_idnumber,
  master_rec_idnumber,
  sys_rule: string
}
