export interface IFixedDeductionCriteriaGroup {
  fd_criteriagrp_spec_id: number,
  criteria_id: number,
  criteria_text: string,
  paygroup_id: number,
  paygroup_text: string,
  fixeddeduct_id: number,
  fixeddeduct_text: string,
  usedirect_amount: boolean,
  currency_id: number,
  currency_text: string,
  direct_amount: number,
  formula_id: number,
  formula_type: string,
  apply_emp_contribution: boolean,
  empcontribute_usedirect_amount: boolean,
  empcontribute_amount: number,
  empcontribute_formula_id: number,
  empcontribute_formula_text: string,
  temp_or_perm: boolean,
  eff_period_from: Date,
  archive_status: boolean,
  approval_status: number,
  eligibility: number,
  eligibility_type_text: string,

  fd_criteria_spec_id: number,
  criteria_title: string,
  criteria_sql: string,
  formula_text: string
}
