export * from './bank.interface';
export * from './calendar.interface';
export * from './criteria-config.interface';
export * from './currency.interface';
export * from './deduct-criteria-config.interface';
export * from './default-currency.interface';
export * from './fixed-allowance.interface';
export * from './fixed-allowance-rate.interface';
export * from './fixed-allowance-employee-rate.interface';
export * from './fixed-allowance-paygroup-rate.interface';
export * from './fixed-deduction-rate.interface';
export * from './fixed-deduction-employee-rate.interface';
export * from './fixed-deduction-paygroup-rate.interface';
export * from './fixed-deduction.interface';
export * from './formula.interface';
export * from './grade.interface';
export * from './last-run.interface';
export * from './paygroup.interface';
export * from './pfa.interface';
export * from './profile.interface';
export * from './run.interface';
export * from './variable-deduction.interface';
export * from './variable-deduction-rate.interface';
export * from './variable-deduction-transaction.interface';
export * from './variable-allowance.interface';
export * from './variable-allowance-rate.interface'
export * from './variable-allowance-transaction.interface';
export * from './default-currency.interface';
export * from './run.interface';
export * from './last-run.interface';
export * from './exclusion-transaction.interface';
export * from './exclusion-transaction-add.interface';
export * from './exclusion-type.interface';
export * from './exclusion-reason.interface';
export * from './exclusion-active-employee.interface';
export * from './exclusion-item-type.interface';
export * from './new-staff-employee.interface';
export * from './new-staff-employee-payroll-profile.interface';
export * from './new-staff-getprofile.interface';
export * from './relief.interface';
export * from './relief-taxrule.interface';
export * from './statutory-relief.interface';
export * from './relief-userule.interface';
export * from './relief.globle.interface';
export * from './relief-grades.interface';
export * from './relief-employee.interface';



export * from './tax-management.interface';

export * from './salary-review-group.interface';
export * from './salary-review-plan.interface';
export * from './salary-review-plan-detail.interface';
