export * from './api-result.interface';

export * from './basic-data.interface';
export * from './name.interface'
export * from './business-option.interface';
export * from './city.interface';
export * from './country.interface';
export * from './currency.interface';
export * from './lga.interface';
export * from './religion.interface';
export * from './state.interface';
export * from './business-type.interface';
export * from './requirement-type.interface';
export * from './dependent-type.interface';
export * from './age-limit.interface';
export * from './doc-max-size.interface';
export * from './select-option.interface';
export * from './parameter.interface';
export * from './nationality-select-option.interface';
export * from './state-select-option.interface';
export * from './error-message.interface';
export * from './form-row.interface';
export * from './form-section.interface';
export * from './to-do.interface';
export * from './anniversary.interface';
export * from './announcement.interface';
