export enum NavMenuItemTypes {
    EVENT_DETAILS = 'EVENT_DETAILS',
    SCHEDULE = 'SCHEDULE',
    PRE_REQUISITES = 'PRE_REQUISITES',
    ASSETS = 'ASSETS',
    PARTICIPANTS = 'PARTICIPANTS',
    FEEDBACK_FORMS = 'FEEDBACK_FORMS',
    FACILITATORS = 'FACILITATORS',
}