export enum LetterStatus {
  INITIATED = 0,
  AWAITING_APPROVAL = 1,
  EXIT_INTERVIEW = 2,
  EXIT_INTERVIEW_COMPLETE = 3,
  CLEARANCE_PROCESS = 4,
  CLEARANCE_PROCESS_COMPLETE = 5,
  PROCESS_COMPLETE = 6,
  PROCESS_CANCELLED = 7,
  REGISTER_ON_ALUMNI = 8
}
