import { Component, OnInit, Input, Inject } from '@angular/core';
import { Observable } from 'rxjs';
import { ITeam } from '@nutela/models/workforce/employee-profiles';
import { Store, select } from '@ngrx/store';
import { IEmployeesProfileState } from '../../../store';
import { LoadApprovedDataTeam, showEditorTeam, showViewerTeam, getTeamApprovedData } from '../../../store/employee-detailed-area';
import { Title } from '@angular/platform-browser';


@Component({
  selector: 'x365-fm-workforce-hr-team',
  templateUrl: './hr-team.component.html',
  styleUrls: ['./hr-team.component.scss']
})
export class HrTeamComponent implements OnInit {
  @Input() employeeId: number;

  showEditor$: Observable<boolean>;
  showViewer$: Observable<boolean>;

  public approvedData$: Observable<ITeam[]>;

  public data = [
    {
      "id": 1,
      "employee_id": 303569,
      "employee_firstname": "Teddy",
      "employee_midname": "Test",
      "employee_surname": "Mich",
      "staff_number": "X365-V2_01",
      "gsm": null,
      "mobile_phone": "08055467873",
      "office_ext": "3567",
      "profile_picture": null,
      "position": null,
      "grade": "EXECUTIVES",
      "username": "dukeo@xceed365.info",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BENIN MAIN OFFICE",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 39,
      "team_role": 0
    },
    {
      "id": 2,
      "employee_id": 1,
      "employee_firstname": "Duke",
      "employee_midname": "JO",
      "employee_surname": "Obasi",
      "staff_number": "D007O",
      "gsm": "08033262700",
      "mobile_phone": "08033262700",
      "office_ext": "302",
      "profile_picture": null,
      "position": "CHIEF EXECUTIVE OFFICER",
      "grade": "EXECUTIVES",
      "username": "dukeobasi@gmail.com",
      "designation": "CHIEF EXECUTIVE OFFICER, (CEO OFFICES)",
      "location_type": "BRANCH",
      "location_details": "CHIBOK HEAD OFFICE",
      "performance_score": null,
      "competency_score": "Restricted",
      "ninebox_location": null,
      "direct_reports": 13,
      "team_role": 1
    },
    {
      "id": 41,
      "employee_id": 3036,
      "employee_firstname": "BILL",
      "employee_midname": "PIUS",
      "employee_surname": "MATT",
      "staff_number": "4BA345S96-P",
      "gsm": null,
      "mobile_phone": "080653452234",
      "office_ext": "122",
      "profile_picture": null,
      "position": "BRANCH MANAGER",
      "grade": "MANAGERS",
      "username": "bill.matt10@xceed365.info",
      "designation": "COORDINATING MANAGER",
      "location_type": "BRANCH",
      "location_details": "LAGOS (HEAD QUARTER)",
      "performance_score": null,
      "competency_score": "No Data",
      "ninebox_location": null,
      "direct_reports": 1,
      "team_role": 3
    },
    {
      "id": 40,
      "employee_id": 100,
      "employee_firstname": "IBRAHIM",
      "employee_midname": "IBRANDR",
      "employee_surname": "ANDREW",
      "staff_number": "3064D297-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "ibrahim.andrew8a1@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 39,
      "employee_id": 99,
      "employee_firstname": "GARUBA",
      "employee_midname": "GAREZIN",
      "employee_surname": "EZINWA",
      "staff_number": "6E1EB83E-E",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "garuba.ezinwa7c7@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 38,
      "employee_id": 98,
      "employee_firstname": "AGADA",
      "employee_midname": "AGAFRAN",
      "employee_surname": "FRANCES",
      "staff_number": "52B1189E-2",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "agada.francesa74@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 37,
      "employee_id": 97,
      "employee_firstname": "MURTALA",
      "employee_midname": "MURABEE",
      "employee_surname": "ABEEB",
      "staff_number": "6654923D-9",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "murtala.abeeb6b8@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 36,
      "employee_id": 96,
      "employee_firstname": "ALILU",
      "employee_midname": "ALIRAYM",
      "employee_surname": "RAYMOND",
      "staff_number": "43D9F778-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": "FINANCIAL SECRETARY",
      "grade": "MANAGERS",
      "username": "alilu.raymond298@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 35,
      "employee_id": 95,
      "employee_firstname": "YUSUF",
      "employee_midname": "YUSOLAI",
      "employee_surname": "OLAITAN",
      "staff_number": "C9381BC4-A",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "yusuf.olaitanbdb@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 34,
      "employee_id": 94,
      "employee_firstname": "MAMODU",
      "employee_midname": "MAMCHIO",
      "employee_surname": "CHIOMA",
      "staff_number": "54BDD610-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "mamodu.chiomac45@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 33,
      "employee_id": 93,
      "employee_firstname": "MGBOKO",
      "employee_midname": "MGBVICT",
      "employee_surname": "VICTOR",
      "staff_number": "E2ED8427-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "mgboko.victor037@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 32,
      "employee_id": 92,
      "employee_firstname": "HILARY-AJODO",
      "employee_midname": "HILRAFI",
      "employee_surname": "RAFIU",
      "staff_number": "65075779-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "hilary-ajodo.rafiu4f8@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 31,
      "employee_id": 91,
      "employee_firstname": "EVANS",
      "employee_midname": "EVAKELV",
      "employee_surname": "KELVIN",
      "staff_number": "E79002C3-F",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "evans.kelvine82@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 30,
      "employee_id": 90,
      "employee_firstname": "OKWUTACHI",
      "employee_midname": "OKWADEW",
      "employee_surname": "ADEWALE",
      "staff_number": "6AA75A7C-1",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "okwutachi.adewalebb7@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 29,
      "employee_id": 89,
      "employee_firstname": "UWODI",
      "employee_midname": "UWONENY",
      "employee_surname": "NENYE",
      "staff_number": "031E7351-B",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "uwodi.nenye686@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 28,
      "employee_id": 88,
      "employee_firstname": "YUSUF",
      "employee_midname": "YUSADEY",
      "employee_surname": "ADEYEMI",
      "staff_number": "B6010196-4",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "yusuf.adeyemie7f@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 27,
      "employee_id": 87,
      "employee_firstname": "OBIDEGWU",
      "employee_midname": "OBIOLAG",
      "employee_surname": "OLAGOKE",
      "staff_number": "8EC94010-F",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "obidegwu.olagokecc8@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 26,
      "employee_id": 86,
      "employee_firstname": "AHIABA",
      "employee_midname": "AHIBRID",
      "employee_surname": "BRIDGET",
      "staff_number": "BBEF1AEE-4",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "ahiaba.bridget00d@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 25,
      "employee_id": 85,
      "employee_firstname": "AJIBADE",
      "employee_midname": "AJIROLI",
      "employee_surname": "ROLI",
      "staff_number": "809EF58C-2",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "ajibade.roli532@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 24,
      "employee_id": 84,
      "employee_firstname": "IZUGBOKWE",
      "employee_midname": "IZUADEJ",
      "employee_surname": "ADEJO",
      "staff_number": "A094C08E-D",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "izugbokwe.adejo043@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 23,
      "employee_id": 83,
      "employee_firstname": "OLAWALE",
      "employee_midname": "OLAIBIR",
      "employee_surname": "IBIRONKE",
      "staff_number": "AB9A802D-A",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "olawale.ibironkefe9@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 22,
      "employee_id": 82,
      "employee_firstname": "ADENE",
      "employee_midname": "ADECHRI",
      "employee_surname": "CHRIS",
      "staff_number": "9608A967-C",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "adene.chris61d@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 21,
      "employee_id": 81,
      "employee_firstname": "ADETURINMO",
      "employee_midname": "ADEKANW",
      "employee_surname": "KANWULIA",
      "staff_number": "1281F5D9-2",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "adeturinmo.kanwulia710@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 20,
      "employee_id": 80,
      "employee_firstname": "SANI",
      "employee_midname": "SANHENR",
      "employee_surname": "HENRY",
      "staff_number": "3A470E02-8",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "sani.henry7de@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 19,
      "employee_id": 79,
      "employee_firstname": "NWACHUKWU",
      "employee_midname": "NWAGODW",
      "employee_surname": "GODWIN",
      "staff_number": "D5879E79-C",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "nwachukwu.godwina66@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 18,
      "employee_id": 78,
      "employee_firstname": "YAHAYA",
      "employee_midname": "YAHSUND",
      "employee_surname": "SUNDAY",
      "staff_number": "A04CF746-0",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "yahaya.sundaye54@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 17,
      "employee_id": 77,
      "employee_firstname": "ADEDAYO",
      "employee_midname": "ADEADEB",
      "employee_surname": "ADEBAYO",
      "staff_number": "317E411B-C",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "adedayo.adebayob8a@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 16,
      "employee_id": 76,
      "employee_firstname": "ASUNNI",
      "employee_midname": "ASUCYNT",
      "employee_surname": "CYNTHIA",
      "staff_number": "7857B403-6",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "OFFICERS",
      "username": "asunni.cynthiaf10@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 15,
      "employee_id": 75,
      "employee_firstname": "SALIU",
      "employee_midname": "SALEMMA",
      "employee_surname": "EMMANUEL",
      "staff_number": "13E25355-4",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "saliu.emmanuel724@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 14,
      "employee_id": 74,
      "employee_firstname": "MOHAMMED",
      "employee_midname": "MOHAUGU",
      "employee_surname": "AUGUSTINE",
      "staff_number": "7FE1975C-7",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "mohammed.augustinefe7@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 13,
      "employee_id": 73,
      "employee_firstname": "AKINDUMILA",
      "employee_midname": "AKICHIN",
      "employee_surname": "CHINWE",
      "staff_number": "3313EFF4-6",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "akindumila.chinwe1aa@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 12,
      "employee_id": 72,
      "employee_firstname": "UDEGBE",
      "employee_midname": "UDEFRAN",
      "employee_surname": "FRANCIS",
      "staff_number": "576ED08C-C",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "udegbe.francise49@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 11,
      "employee_id": 71,
      "employee_firstname": "UMEH",
      "employee_midname": "UMEOKEB",
      "employee_surname": "OKEBOLA",
      "staff_number": "20D77AA7-C",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "umeh.okebola50c@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "IDEMILI BRANCH",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 10,
      "employee_id": 70,
      "employee_firstname": "LAWAL",
      "employee_midname": "LAWIKEC",
      "employee_surname": "IKECHI",
      "staff_number": "00FE749B-4",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "lawal.ikechie79@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 9,
      "employee_id": 69,
      "employee_firstname": "MMDUAKONAM",
      "employee_midname": "MMDABAY",
      "employee_surname": "ABAYOMI",
      "staff_number": "BEF2BF35-F",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "EXECUTIVES",
      "username": "mmduakonam.abayomid70@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 8,
      "employee_id": 68,
      "employee_firstname": "OWADARA",
      "employee_midname": "OWABAMI",
      "employee_surname": "BAMIDELE",
      "staff_number": "4E930054-9",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "owadara.bamidele9a9@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Danger",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 7,
      "employee_id": 67,
      "employee_firstname": "OKOCHA",
      "employee_midname": "OKOADEG",
      "employee_surname": "ADEGBOYEGA",
      "staff_number": "46E694D7-6",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "okocha.adegboyegad20@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 6,
      "employee_id": 66,
      "employee_firstname": "ALFA",
      "employee_midname": "ALFCHUK",
      "employee_surname": "CHUKWUDI",
      "staff_number": "B69599C8-9",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "alfa.chukwudi4f8@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 5,
      "employee_id": 65,
      "employee_firstname": "FOWOWE",
      "employee_midname": "FOWLEON",
      "employee_surname": "LEONARD",
      "staff_number": "C1ED1FAA-4",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "fowowe.leonard115@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Healthy",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 4,
      "employee_id": 64,
      "employee_firstname": "ONWUBORU",
      "employee_midname": "ONWNWAN",
      "employee_surname": "NWANJA",
      "staff_number": "060FF9E6-B",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "onwuboru.nwanja260@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Focus",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    },
    {
      "id": 3,
      "employee_id": 63,
      "employee_firstname": "AJAEGBU",
      "employee_midname": "AJADICK",
      "employee_surname": "DICKSON",
      "staff_number": "34B92E54-6",
      "gsm": null,
      "mobile_phone": null,
      "office_ext": null,
      "profile_picture": null,
      "position": null,
      "grade": "MANAGERS",
      "username": "ajaegbu.dickson056@xceed365.com",
      "designation": null,
      "location_type": "BRANCH",
      "location_details": "BRANCH 097-GRP",
      "performance_score": null,
      "competency_score": "Caution",
      "ninebox_location": null,
      "direct_reports": 0,
      "team_role": 3
    }
  ]

  constructor(@Inject('partialDocumentTitle')
  private partialDocumentTitle: string,
  private titleService: Title,
  private store: Store<IEmployeesProfileState>,) {
    titleService.setTitle(
      `${'HR Team'}${this.partialDocumentTitle}`
    );
  }

  ngOnInit() {
    this.storeDispatches();
    this.storeSelects();
  }

  storeDispatches() {
    this.store.dispatch(new LoadApprovedDataTeam({ employeeId: this.employeeId }));
  }

  storeSelects() {
    this.showEditor$ = this.store.pipe(select(showEditorTeam));
    this.showViewer$ = this.store.pipe(select(showViewerTeam));

    this.approvedData$ = this.store.pipe(select(getTeamApprovedData));
  }
}
