export * from './general-information.service';
export * from './profile-picture.service';
export * from './contact.service';
export * from './identification.service';
export * from './payment.service';
export * from './beneficiary.service';
export * from './dependant.service';
export * from './educational-history.service';
export * from './family.service';
export * from './guarantor.service';
export * from './personal-referee.service';
export * from './professional-qualification.service';
export * from './work-history.service';
export * from './hr-custom-data-form.service'
