
export const COMPENSATION_MODULES = {
  "PAYROLL": "PAYROLL",
  "BENEFITS": "BENEFITS",
  "PAYMENTS": "PAYMENTS",
  "LOANS": "LOANS",
  "REWARDS": "REWARDS",
  "EXPENSE": "EXPENSE",
  "TAX_AND_STATUTORY": "TAX_AND_STATUTORY",
  "REMITTANCE": "REMITTANCE"
};
