
export const PLATFORM_MODULES = {
  "HR_FOUNDATIONS": "HR_FOUNDATIONS",
  "LOOKUPS": "LOOKUPS",
  "PROVISIONING": "PROVISIONING",
  "DATA_ADMINISTRATION": "DATA_ADMINISTRATION",
  "DYNAMIC_PROCESS": "DYNAMIC_PROCESS",
  "EXIT_MANAGEMENT": "EXIT_MANAGEMENT",
  "WIP": "WIP"
};
