
export const TALENT_MODULES = {
  "RECRUIT": "RECRUIT",
  "LEARNING": "LEARNING",
  "PERFORMANCE": "PERFORMANCE",
  "COMPETENCY": "COMPETENCY",
  "SUCCESSION_AND_CAREER": "SUCCESSION_AND_CAREER",
  "MENTORSHIP": "MENTORSHIP"
};
