
export const WORKFORCE_MODULES = {
  EMPLOYEE_PROFILES: "EMPLOYEE_PROFILES",
  PROCESSES: "HR_CUSTOM_PROCESS",
  SCANNED_DOCUMENTS: "SCANNED_DOCUMENTS",
  ALUMNI: "ALUMNI",
  REFERENCES: "REFERENCES",
  ABSENCE: "ABSENCE",
  MEDICALS: "MEDICALS",
  GLOBAL_DEPLOYMENT: "GLOBAL_DEPLOYMENT",
  SEPARATION: "SEPARATION",
  SUBSCRIPTION: "SUBSCRIPTION",
  EXIT_MANAGEMENT: "EXIT_MANAGEMENT",
};
