export enum AssetTypes {
  CUSTOM_PAGE = 0,
  KPI_PAGE = 1,
  RATING_PAGE = 2,
  CONTRACT_PAGE = 3,
  COMPETENCY_PAGE = 4,
  SUBSCRIPTION_PAGE = 5,
  THREE_SIXTY_RATING_PAGE = 6,
  RATING_FEEDBACK_PAGE = 7
}
